[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tangods_prevacm600dc"
description = "pytango device server to control the Prevac M600DC power supply"
# add the keywords for your project here
keywords = ["tango device", "tango", "pytango"]
readme = "README.md"
authors = [
    {name = "Michael Schneider"},
]
requires-python = ">=3.10"
# add the dependencies for your project here
dependencies = ["numpy", "pytango", "pymodbus"]
license = {text = "MIT"}
# specify the version of the package in the VERSION file
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/MBI-Div-B/pytango-PrevacM600DC"

[project.scripts]
# specife the name of the executable on the left hand side and the entry_point on the right hand side
PrevacM600DC = "tangods_prevacm600dc:main"

[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.setuptools.packages.find]

[tool.setuptools.package-data]
# change the name of the package to the name of your package and add the files that should be included in the package
tangods_prevacm600dc = ["VERSION"]
"tangods_prevacm600dc.calibration" = ["*.txt"]
